Put barcode generator into action
This is the first version with the kbarcode barcode generator window. This version uses many deprecated classes and members used by the barcode generator.

Add KDE4_KDE3SUPPORT_LIBS into target_link_libraries() in CMakeLists.txt . Otherwise compiler produces a link error "undefined reference to" K3Wizard, K3Command, etc..

executable: tmp/bin/kbarcode009
Compilation Errors: None.
Compilation Warnings: "operator== is incomplete" when compiling barkode.cpp .
    Several warnings - unused variable.
    Many warnings deprecated and others.
Runtime Errors: None.
Runtime Warnings: 6 : 1) Prefix changed: ...,
    2) QFSFileEngine::open: No file name specified
    Cannot read validation rules from
    3) 2 warnings after moving the mouse cursor over confassistant dialog:
    QInotifyFileSystemWatcherEngine::addPaths: ...
    QFileSystemWatcher: failed to add paths: /home/fanda/.config/ibus/bus
    4) Warnings after an attempt to connect to a database:
    QSqlDatabasePrivate::removeDatabase ...,
    QSqlQuery::exec: database not open
    Can't import data, dabase not open!
    5) Warnings triggered when creating a databasebrowser widget like so:
    Q3SqlCursor::setName: unable to build record, does 'label_def' exist?
    6) When using the barcode generator: barcode: can't encode "12345678"
Uses QT3/KDE3: Yes.
new files in kbarcode_SRCS: barcodecombo.cpp, barcodegenerator.cpp, commands.cpp,
    dstextedit.cpp, imageitem.cpp, mimesources.cpp, mycanvasview.cpp,
    dialogs/barcodedialogs.cpp, dialogs/tokendialog.cpp,
new files:
Using source files: barcodecombo.cpp, barcodegenerator.cpp, barcodeitem.cpp,
    barkode.cpp, barkodeengine.cpp,
    commands.cpp, confassistant.cpp, csvfile.cpp,
    databasebrowser.cpp, definition.cpp, documentitem.cpp,
    dsrichtext.cpp, dstextedit.cpp, encodingcombo.cpp,
    gnubarcode.cpp, imageitem.cpp, kbarcode.cpp,
    kbarcodesettings.cpp, labelutils.cpp, lineitem.cpp,
    main.cpp, mainwindow.cpp, measurements.cpp, mimesources.cpp,
    mycanvasitem.cpp, mycanvasview.cpp, mydatatable.cpp,
    pixmapbarcode.cpp, printersettings.cpp, purepostscript.cpp,
    rectitem.cpp, sqltables.cpp, tbarcode2.cpp, tcanvasitem.cpp,
    textitem.cpp, textlineitem.cpp, tokenprovider.cpp, xmlutils.cpp,
    zplutils.cpp,
    dialogs/barcodedialogs.cpp, dialogs/configdialog.cpp, dialogs/csvimportdlg.cpp,
    dialogs/tokendialog.cpp,